### ISSUE TITLE
Why True and False work like this?!

### ISSUE THREAD

**Issue by derarmealex** [derarmealex/python-learning-syntax#1]
https://github.com/derarmealex/python-learning-syntax/blob/2e0e1eb0c4229c5151f0be3a7401dd5dd404b9ea/true_false_sic.py
![true_false_sic](https://github.com/derarmealex/python-learning-syntax/assets/140951167/b1692d55-d6d7-4ef1-b9a6-7bf2dfa633d8)

**Comment by Ahmad1015** [comment]
Line 2: In the expression print(bool(False and False == False)), we have the logical AND operator between two values. Simplifying this, we get print(bool(False and True)).
We get True on the other side as False is equal to False. The AND operator returns True only when both operands are True. In this case, the second operand is True, not the first one. So, The expression simplifies to print(bool(False)), and the final result is False.

Line 23: Let's examine the expression print(bool(True or True == False)), which involves the logical OR operator. When using the OR operator, the output is True if at least one operand is True, regardless of the second value. So, simplifying this correctly, we get print(bool(True or False)), which gives us the correct final result of True.

Using this, you can figure out the other similar queries you have in this question. 😊

**Comment by derarmealex** [comment]
Thx a lot... :)
Nope, unfortunately I can't figure out other examples because if I probably can get now when:

**`print(bool(False and False == False))`**   _#False_
and
**`print(bool(False and True == False))`**    _#False_

I then just have no idea why outputs are different as soon as we just swap the operators:

**`print(bool(False and True == False))`**    _#False_
**`print(bool(True and False == False))`**    _#True_

if it still goes that:

**`print(bool(True and False))`**                   _#False_
**`print(bool(False and True))`**                  _#False_

at least I hope the point is going to come to me yet... :)

**Comment by derarmealex** [comment]
> Line 2: In the expression print(bool(False and False == False)), we have the logical AND operator between two values. Simplifying this, we get print(bool(False and True)). We get True on the other side as False is equal to False. The AND operator returns True only when both operands are True. In this case, the second operand is True, not the first one. So, The expression simplifies to print(bool(False)), and the final result is False.
> 
> Line 23: Let's examine the expression print(bool(True or True == False)), which involves the logical OR operator. When using the OR operator, the output is True if at least one operand is True, regardless of the second value. So, simplifying this correctly, we get print(bool(True or False)), which gives us the correct final result of True.
> 
> Using this, you can figure out the other similar queries you have in this question. 😊

Thx a lot... :)
Nope, unfortunately I can't figure out other examples because if I probably can get now when:

**`print(bool(False and False == False))`**   _#False_
and
**`print(bool(False and True == False))`**    _#False_

I then just have no idea why outputs are different as soon as we just swap the operators:

**`print(bool(False and True == False))`**    _#False_
**`print(bool(True and False == False))`**    _#True_

if it still goes that:

**`print(bool(True and False))`**                   _#False_
**`print(bool(False and True))`**                  _#False_

at least I hope the point is going to come to me yet... :)

**Comment by Ahmad1015** [comment]
To speed up the process of boolean evaluation , python uses Short circuit Evaluation. Short-circuit evaluation means that when evaluating Boolean expression like AND and OR, we can stop as soon as we find the first condition which satisfies or negates the expression. By short-circuiting we mean the stoppage of execution of boolean operation if the truth value of expression has been determined already.
 Incase of an "or" expression, the python interpreter first takes the first statement and check to see if is true. When the first statement is true, then python returns that object’s value without looking into the second argument. This is because for an or expression, the whole thing is true if one of the values is true; and the program doesn’t look into second statement. However, if the first object value evaluates to false, python checks the second statement and returns that value. The second half determines the truth value of the expression since the first half was false. This process of interpreter is called “short-circuiting”. It is a common way of evaluating Boolean expression in many programming languages.

Similarly, for an "and" expression, python uses a short circuit technique to speed truth value evaluation. If the first statement is false then the whole thing must be false and it returns that object value (false) else, if the first value is true it checks the second and returns that value.

**Comment by derarmealex** [comment]
> To speed up the process of boolean evaluation , python uses Short circuit Evaluation. Short-circuit evaluation means that when evaluating Boolean expression like AND and OR, we can stop as soon as we find the first condition which satisfies or negates the expression. By short-circuiting we mean the stoppage of execution of boolean operation if the truth value of expression has been determined already. Incase of an "or" expression, the python interpreter first takes the first statement and check to see if is true. When the first statement is true, then python returns that object’s value without looking into the second argument. This is because for an or expression, the whole thing is true if one of the values is true; and the program doesn’t look into second statement. However, if the first object value evaluates to false, python checks the second statement and returns that value. The second half determines the truth value of the expression since the first half was false. This process of interpreter is called “short-circuiting”. It is a common way of evaluating Boolean expression in many programming languages.
> 
> Similarly, for an "and" expression, python uses a short circuit technique to speed truth value evaluation. If the first statement is false then the whole thing must be false and it returns that object value (false) else, if the first value is true it checks the second and returns that value.

Thank you very much. I think it got to me. :) Evidently for working with large date array, working with pieces of code located in different parts/modules or analogous cases, that's more suitable way of evaluating even if it looks a bit more complicated for civilian view. :)
Btw. as I noticed, in simple cases if you just must evaluate every operand for some reasons, you can have the first part of expression in brackets, then Python will evaluate the whole part before "=="  like this: **bool((False and False) == False** _# True_

**Comment by Ahmad1015** [comment]
Interesting! Short Circuit Evaluation is used to speed up the decision-making process. However, if you want to ensure that both decisions are checked, you can use brackets, although it is not preferred as it slows you down. Instead, it is better to write the condition with higher priority first, followed by the logical operator, and then the other decision. This way, Python bases its decision on the more important decision-making expression.😊

**Comment by derarmealex** [comment]
> Interesting! Short Circuit Evaluation is used to speed up the decision-making process. However, if you want to ensure that both decisions are checked, you can use brackets, although it is not preferred as it slows you down. Instead, it is better to write the condition with higher priority first, followed by the logical operator, and then the other decision. This way, Python bases its decision on the more important decision-making expression.😊

🙏
